services:
  - type: web
    name: squad-coordinator
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 